export const REMOVE_CIRCLE_FROM_QUEUE=`REMOVE_CIRCLE_FROM_QUEUE`;
export const REMOVED_FROM_CONTAINER = `REMOVED_FROM_CONTAINER`;
export const ADD_CIRCLE_IN_CONTAINER = `ADD_CIRCLE_IN_CONTAIER`;
export const REMOVE_FROM_CONTAINER_ADD_IN_QUEUE=`REMOVE_FROM_CONTAINER_ADD_IN_QUEUE`;